spring:
  application:
    name: java-rag-local

  datasource:
    url: jdbc:postgresql://localhost:5432/rag_db
    username: postgres
    password: 123456

  data:
    redis:
      host: localhost
      port: 6379
      database: 0

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  ai:
    ollama:
      base-url: http://localhost:11434

    vectorstore:
      pgvector:
        dimensions: 1024
        index-type: NONE
        initialize-schema: true

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    max-http-form-post-size: 200MB
    max-swallow-size: 200MB

app:
  zhipu:
    api-key: ${ZHIPU_API_KEY:}
    chat-model: glm-4.6v
    chat-url: https://open.bigmodel.cn/api/paas/v4/chat/completions

  rag:
    docs-path: classpath:/docs/*.docx
    top-k: 10
    final-top-k: 3
    max-context-chars: 4000
    max-history-messages: 6
    max-history-tokens: 3000
    use-llm-rerank: true

logging:
  level:
    org.apache.pdfbox.pdmodel.font.FileSystemFontProvider: ERROR