spring.application.name=java-rag-local

# Zhipu API
app.zhipu.api-key=${ZHIPU_API_KEY}
app.zhipu.chat-model=glm-4-flash
app.zhipu.embedding-model=embedding-3
app.zhipu.embedding-url=https://open.bigmodel.cn/api/paas/v4/embeddings
app.zhipu.chat-url=https://open.bigmodel.cn/api/paas/v4/chat/completions

# RAG
app.rag.docs-path=classpath:/docs/*.docx
app.rag.top-k=4


# Reduce noisy PDF font warnings
logging.level.org.apache.pdfbox.pdmodel.font.FileSystemFontProvider=ERROR
